### ISSUE TITLE
Can't be used with `extends` as it declare `depends_on`

### ISSUE THREAD

**Issue by Ducote** [synzen/MonitoRSS#371] opened 2024-03-14 23:12 UTC
## Describe the bug

Building with docker compose won't work on recent version.

## To Reproduce

Follow the tutorial :
1. Clone git main branch.
2. (Optionnal) Complete .env.prod.
3. Use `docker compose up -d`

## Expected behavior

service "discord-rest-listener-service" can't be used with `extends` as it declare `depends_on`

## Observed behavior

MonitoRSS building

## Screenshots

![image](https://github.com/synzen/MonitoRSS/assets/48557328/805f084d-dfaf-4baf-9daf-57af4e0b73b0)

## Branch (please specify one):

main

## Additional context

Docker version 25.0.4, build 1a576c5
Docker Compose version v2.24.7
Ubuntu 22.04.4 LTS

When trying to resolve this issue, other services have this error.

**Comment by synzen** [comment] 2024-03-18 11:02
Apologies for the delay in my response - it appears this is a known issue with the more recent versions of docker/docker compose: https://github.com/docker/compose/issues/11544

I'm having trouble understanding its release process to see when it will be fixed, but I assume that once the issue is closed, you can try updating docker for it to be resolved

In the meantime, I can confirm that Docker Engine 25.03/Docker Compose v2.24.5 appears to work on my end, if you're able to pin the version that you're using

**Comment by Ducote** [comment] 2024-03-18 11:07
I pinned both versions in additional context. Heree they are :
- Docker version 25.0.4, build 1a576c5
- Docker Compose version v2.24.7

**Comment by synzen** [comment] 2024-03-18 12:18
Apologies for the confusion - when I said pin the version, I mean directly set the version that you're using to match what I mentioned

**Comment by Ducote** [comment] 2024-03-19 10:45
I apologise, I must be missing something, or maybe I did something wrong.

Here's (maybe) what's the closest to an answer I can give you.

Partial result from my history
```
  776  git clone https://github.com/synzen/MonitoRSS.git
  777  cd MonitoRSS/
  778  ls
  779  cp .env.example .env.prod
  780  nano .env.prod 
  781  docker compose up -d
  782  docker compose --parallel 1 up -d
```

According to stat command, I cloned the repos on 2024-03-14 22:54:12.523349029 +0000

**Comment by mustafasegf** [comment] 2024-03-19 11:11
> I apologise, I must be missing something, or maybe I did something wrong.
> 
> Here's (maybe) what's the closest to an answer I can give you.
> 
> Partial result from my history
> ```
>   776  git clone https://github.com/synzen/MonitoRSS.git
>   777  cd MonitoRSS/
>   778  ls
>   779  cp .env.example .env.prod
>   780  nano .env.prod 
>   781  docker compose up -d
>   782  docker compose --parallel 1 up -d
> ```
> 
> According to stat command, I cloned the repos on 2024-03-14 22:54:12.523349029 +0000

Hi there, you didn't do anything wrong. There's a bug in docker compose and it got fixed in the latest release. Try to upgrade your docker compose version to 2.25.0

**Comment by synzen** [comment] 2024-03-19 22:15
Thanks for confirming @mustafasegf

**Closed by synzen** 2024-03-19 22:15 UTC
